name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run Tests
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=./TestResults/coverage.json
    - name: Install Code Coverage Report Generator
      run: dotnet tool install dotnet-reportgenerator-globaltool --tool-path Tools
    - name: Generate Code Coverage Report
      run: ./Tools/reportgenerator -reports:./TestResults/coverage.json -targetdir:./TestResults/Coverage -reporttypes:lcov
